/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.h
  * @brief          : Header for main.c file.
  *                   This file contains the common defines of the application.
  *
  * Project : Multi-Purpose Digital Clock using STM32F446RE
  * Features:
  *   - RTC-based 24-hour clock
  *   - Stopwatch using system tick
  *   - Time-setting interface via push buttons
  *   - 16x2 LCD in 4-bit parallel mode
  *
  * Author  : Jayant Chopra (24UEC114)
  * College : LNMIIT, ECE Department
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2025 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __MAIN_H
#define __MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "stm32f4xx_hal.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
/**
 * @brief Application-wide includes
 *
 * Additional headers (like parallel_lcd.h) are included
 * in main.c to keep hardware abstraction modular.
 */
/* USER CODE END Includes */

/* Exported types ------------------------------------------------------------*/
/* USER CODE BEGIN ET */
/*
 * Exported application-level types (if any) can be placed here.
 * Currently, mode/state enums are defined directly in main.c
 * for closer coupling with application logic.
 */
/* USER CODE END ET */

/* Exported constants --------------------------------------------------------*/
/* USER CODE BEGIN EC */
/* User-defined global constants can be declared here if needed. */
/* USER CODE END EC */

/* Exported macro ------------------------------------------------------------*/
/* USER CODE BEGIN EM */
/* Useful helper macros for the entire application can be added here. */
/* USER CODE END EM */

/* Exported functions prototypes ---------------------------------------------*/
void Error_Handler(void);

/* USER CODE BEGIN EFP */
/**
 * @brief Application-specific exported function prototypes
 *
 * Currently, only Error_Handler() is exposed globally.
 * All other functions are kept file-local in main.c or
 * in driver modules (e.g., parallel_lcd.c).
 */
/* USER CODE END EFP */

/* Private defines -----------------------------------------------------------*/
/* USER CODE BEGIN Private defines */
/**
 * ===================== GPIO PIN MAPPING =====================
 * These pins are generated by STM32CubeMX and represent the
 * physical connections between STM32F446RE and peripherals:
 *
 * - reset_pin       : Stopwatch reset / increment button (PC0)
 * - start_stop_pin  : Start/Stop / select button (PB8)
 * - mode_pin        : Mode change button (PB9)
 *
 * - LCD_D4..D7      : 4-bit data lines to 16x2 LCD
 * - LCD_RS          : Register Select (command/data select)
 * - LCD_EN          : Enable pin to latch data into LCD
 *
 * The logical abstraction (LCD_RS_PORT, etc.) is defined in
 * parallel_lcd.h so that the driver code remains clean.
 * ===========================================================
 */
/* USER CODE END Private defines */

#define reset_pin_Pin GPIO_PIN_0
#define reset_pin_GPIO_Port GPIOC

#define LCD_D6_Pin GPIO_PIN_10
#define LCD_D6_GPIO_Port GPIOB

#define LCD_D7_Pin GPIO_PIN_8
#define LCD_D7_GPIO_Port GPIOA

#define LCD_RS_Pin GPIO_PIN_10
#define LCD_RS_GPIO_Port GPIOA

#define LCD_EN_Pin GPIO_PIN_3
#define LCD_EN_GPIO_Port GPIOB

#define LCD_D5_Pin GPIO_PIN_4
#define LCD_D5_GPIO_Port GPIOB

#define LCD_D4_Pin GPIO_PIN_5
#define LCD_D4_GPIO_Port GPIOB

#define start_stop_pin_Pin GPIO_PIN_8
#define start_stop_pin_GPIO_Port GPIOB

#define mode_pin_Pin GPIO_PIN_9
#define mode_pin_GPIO_Port GPIOB

#ifdef __cplusplus
}
#endif

#endif /* __MAIN_H */
