#ifndef PARALLEL_LCD_H
#define PARALLEL_LCD_H

#include "main.h"
#include <stdint.h>

/**
 * @file    parallel_lcd.h
 * @brief   Interface definitions for 16x2 HD44780 LCD in 4-bit mode
 *
 * This header contains:
 *  - Pin mapping between STM32 GPIO and LCD signals
 *  - Command and flag definitions for HD44780 controller
 *  - Public function prototypes for LCD control and printing
 *
 * The actual implementation is in parallel_lcd.c.
 */

/* ================== LCD PIN MAPPING ==================
 * All pin names (LCD_RS_Pin, LCD_D4_Pin, etc.) are
 * generated by STM32CubeMX in main.h / gpio.h.
 *
 * These macros create a clear abstraction layer so that
 * the LCD driver uses logical names (LCD_RS_PORT, etc.)
 * and the actual hardware pins can be changed in CubeMX
 * without modifying the driver.
 * ==================================================== */

// Register Select (RS) pin: 0 = command, 1 = data
#define LCD_RS_PIN      LCD_RS_Pin
#define LCD_RS_PORT     LCD_RS_GPIO_Port

// Enable (EN) pin: used to latch data into LCD
#define LCD_EN_PIN      LCD_EN_Pin
#define LCD_EN_PORT     LCD_EN_GPIO_Port

// Data lines for 4-bit mode (D4–D7)
#define LCD_D4_PIN      LCD_D4_Pin
#define LCD_D4_PORT     LCD_D4_GPIO_Port

#define LCD_D5_PIN      LCD_D5_Pin
#define LCD_D5_PORT     LCD_D5_GPIO_Port

#define LCD_D6_PIN      LCD_D6_Pin
#define LCD_D6_PORT     LCD_D6_GPIO_Port

#define LCD_D7_PIN      LCD_D7_Pin
#define LCD_D7_PORT     LCD_D7_GPIO_Port

/* ================== BUTTON PIN MAPPING ==================
 * Button pins are also generated by CubeMX and mapped here
 * for readability in the main application.
 * ======================================================= */

#define MODE_BUTTON_PIN      mode_pin_Pin
#define MODE_BUTTON_PORT     mode_pin_GPIO_Port

#define START_STOP_PIN       start_stop_pin_Pin
#define START_STOP_PORT      start_stop_pin_GPIO_Port

#define RESET_PIN            reset_pin_Pin
#define RESET_PORT           reset_pin_GPIO_Port

/* ================== LCD COMMAND BASE CODES ==================
 * These are the base opcodes from the HD44780 datasheet.
 * They are combined with flags below to form full commands.
 * =========================================================== */

#define LCD_CMD_CLEAR           0x01    // Clear display and return cursor home
#define LCD_CMD_HOME            0x02    // Return cursor to home position
#define LCD_CMD_ENTRY_MODE      0x04    // Entry mode set
#define LCD_DISPLAY_CTRL        0x08    // Display on/off control
#define LCD_CMD_CURSOR_SHIFT    0x10    // Cursor or display shift
#define LCD_CMD_FUNCTION_SET    0x20    // Interface data length, lines, font
#define LCD_CMD_SET_CGRAM       0x40    // Set CGRAM address (custom chars)
#define LCD_CMD_SET_DDRAM       0x80    // Set DDRAM address (display)

// Entry mode flags (to be OR'ed with LCD_CMD_ENTRY_MODE)
#define LCD_ENTRY_LEFT          0x02    // Cursor moves left
#define LCD_ENTRY_RIGHT         0x00    // Cursor moves right
#define LCD_ENTRY_SHIFT_ON      0x01    // Display shift enabled
#define LCD_ENTRY_SHIFT_OFF     0x00    // Display shift disabled

// Display control flags (to be OR'ed with LCD_DISPLAY_CTRL)
#define LCD_DISPLAY_ON          0x04
#define LCD_DISPLAY_OFF         0x00
#define LCD_CURSOR_ON           0x02
#define LCD_CURSOR_OFF          0x00
#define LCD_BLINK_ON            0x01
#define LCD_BLINK_OFF           0x00

// Cursor/display shift flags (to be OR'ed with LCD_CMD_CURSOR_SHIFT)
#define LCD_SHIFT_DISPLAY       0x08    // Shift entire display
#define LCD_SHIFT_CURSOR        0x00    // Move cursor only
#define LCD_SHIFT_RIGHT         0x04
#define LCD_SHIFT_LEFT          0x00

// Function set flags (to be OR'ed with LCD_CMD_FUNCTION_SET)
#define LCD_8BIT_MODE           0x10
#define LCD_4BIT_MODE           0x00
#define LCD_2LINE               0x08
#define LCD_1LINE               0x00
#define LCD_5x10_DOTS           0x04
#define LCD_5x8_DOTS            0x00

/* ================== COMMON PRECOMPOSED COMMANDS ==================
 * These are ready-to-use commands formed by combining the base
 * opcodes and flags. Many of them come directly from your
 * HD44780 reference table.
 * ================================================================ */

#define LCD_DEC_CURSOR          0x04    // Decrement cursor (shift left)
#define LCD_INC_CURSOR          0x06    // Increment cursor (shift right)
#define LCD_SHIFT_DISPLAY_R     0x05    // Shift display right
#define LCD_SHIFT_DISPLAY_L     0x07    // Shift display left

#define LCD_DISP_OFF_CURS_OFF   0x08    // Display off, cursor off
#define LCD_DISP_OFF_CURS_ON    0x0A    // Display off, cursor on
#define LCD_DISP_ON_CURS_OFF    0x0C    // Display on, cursor off
#define LCD_DISP_ON_CURS_BLINK  0x0F    // Display on, cursor blinking

#define LCD_SHIFT_CURSOR_L      0x10    // Move cursor left
#define LCD_SHIFT_CURSOR_R      0x14    // Move cursor right
#define LCD_SHIFT_DISP_L        0x18    // Shift entire display left
#define LCD_SHIFT_DISP_R        0x1C    // Shift entire display right

#define LCD_LINE1_START         0x80    // DDRAM address of line 1, position 0
#define LCD_LINE2_START         0xC0    // DDRAM address of line 2, position 0

#define LCD_2LINE_5x7           0x38    // 8-bit, 2 lines, 5x7 font (for reference)

/* ================== PUBLIC API: CORE FUNCTIONS ==================
 * These are the main functions used by the application.
 * The rest of the project should only use these and not
 * worry about low-level timing or pin toggling.
 * ================================================================ */

// Initialize LCD in 4-bit mode and configure basic settings
void LCD_Init(void);

// Clear entire display and return cursor home
void LCD_Clear(void);

// Return cursor to (0,0) (if implemented in .c)
void LCD_Home(void);

// Set cursor to given row and column (0-based indexing)
void LCD_SetCursor(uint8_t row, uint8_t col);

/* ================== DISPLAY CONTROL FUNCTIONS ==================
 * Optional helpers that wrap common display configurations.
 * =============================================================== */

void LCD_DisplayOn(void);
void LCD_DisplayOff(void);
void LCD_CursorOn(void);
void LCD_CursorOff(void);
void LCD_BlinkOn(void);
void LCD_BlinkOff(void);

/* ================== SHIFT FUNCTIONS ==================
 * Helpers for moving cursor or shifting display contents.
 * ===================================================== */

void LCD_ShiftLeft(void);
void LCD_ShiftRight(void);
void LCD_ShiftDisplayLeft(void);
void LCD_ShiftDisplayRight(void);

/* ================== TEXT OUTPUT FUNCTIONS ==================
 * Higher-level interfaces for writing characters and
 * strings to the LCD.
 * ========================================================== */

// Write a single character at current cursor position
void LCD_WriteChar(char ch);

// Write null-terminated string starting at current cursor
void LCD_WriteString(char *str);

// Set position and then write string
void LCD_WriteStringXY(uint8_t row, uint8_t col, char *str);

// printf-style formatted print to LCD
void LCD_Print(char *format, ...);

/* ================== CUSTOM CHARACTER FUNCTIONS ==================
 * Allows defining up to 8 custom characters (locations 0–7).
 * These are stored in CGRAM and can be displayed by writing
 * character code 0–7 with LCD_WriteChar().
 * ================================================================ */

// Define a custom character pattern at CGRAM location (0..7)
void LCD_CreateChar(uint8_t location, uint8_t charmap[]);

// Write pre-defined custom char at current cursor
void LCD_WriteCustomChar(uint8_t location);

#endif
